import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Sidebar from "@/components/sidebar";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Smart High Ai",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
        />
        <title>Smart High Ai</title>
      </head>
      <body
        style={{
          height: "100vh",
        }}
      >
        {/* Layout UI */}
        {/* Place children where you want to render a page or nested layout */}
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            height: "100vh",

            background: "white",
            color: "black",
            margin: "10px 10px",
          }}
        >
          <Header />
          <div style={{ display: "flex", flex: 1 }}>
            <Sidebar />
            <main style={{ flex: 1, padding: "26px 16px" }}>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
